### ISSUE TITLE
Software referenced no longer exists

### ISSUE THREAD

**Issue by cloudpitchford** [ibm-cloud-docs/iaas-vpn#20]
Not listed among the closed options (and I don't have a link to the staging repo yet), but there is software: https://itunes.apple.com/us/app/motionpro-plus/id1218085720?mt=12 that has changed its name since https://cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-connect-ssl-vpn-mac-osx#connect-ssl-vpn-mac-osx was written.

In addition, the software as it now exists has been criticized, and may have issues preventing it from being useful in this area? Thanks.

**Comment by mjeynes** [comment]
I agree.  IBM needs to investigate why SSL VPN from Mac using MotionPro 2.0.1 (the only version available via Apple) is not stable.  VPN connections freeze and become unusable with MANUAL restart the only workaround, often only effective for a few minutes.

**Comment by Esmint** [comment]
The folder structure that IBM refers to does not exist:
/usr/local/motionpro/
