### ISSUE TITLE
Cannot connect to VPN using MAC OS

### ISSUE THREAD

**Issue by elgiet** [ibm-cloud-docs/iaas-vpn#21]
Unable to connect to VPN via vpn.tok02.softlayer.com. User tried the following instructions found in https://cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-connect-ssl-vpn-mac-osx#connect-ssl-vpn-mac-osx. User also tried accessing different end point vpn.seo01.softlayer.com but encountered the same error.

![image](https://user-images.githubusercontent.com/49508436/56481675-cb77cc80-64f2-11e9-947a-f94f480b2706.png)

**Comment by Esmint** [comment]
That folder /usr/local/motionpro/ does not exist anymore after installing it.

**Comment by austinmama** [comment]
Updated instructions and tested by OM - Brandon Wright.  Closing.

https://test.cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-connect-ssl-vpn-mac-osx
