### ISSUE TITLE
Linux client fails to connect but Windows client works: MotionPro_Linux_RedHat_x86-64_1.2.3.sh fails on RHEL 7.5 

### ISSUE THREAD

**Issue by UzK98fYoE** [ibm-cloud-docs/iaas-vpn#25]
Steps to reproduce the problem:
1.  wget https://support.arraynetworks.net/prx/001/http/supportportal.arraynetworks.net/downloads/pkg_9_4_0_273/MP_Linux_1.2.3/MotionPro_Linux_RedHat_x86-64_1.2.3.sh
2. sudo bash MotionPro_Linux_RedHat_x86-64_1.2.3.sh
3. MotionPro --host vpn.wdc04.softlayer.com

Output is:
```
 MotionPro --host vpn.wdc04.softlayer.com
Only one method: localdb
Input username: [snip]
Input password for localdb:
login successfully!
starting vpn...
current status:0
current status:0
Connect successfully!
Vpn is connected!

nc -vz 10.166.140.143 22
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connection timed out.
```

When I connect using the Windows client, it works:
![image](https://user-images.githubusercontent.com/33329349/61892827-3e1d8d00-aed2-11e9-833e-732941e44cf8.png)

More details:
```
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
$
```

**Comment by seanw2020** [comment]
Yay! I got this working. The problem was the endpoint, vpn.wdc04.softlayer.com, which does NOT support the Linux client, as suggested here: https://cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-standalone-vpn-clients 

This command worked on Ubuntu 16.04 with the 1.2.3 VPN client:
```
MotionPro --host vpn.dal12.softlayer.com --user me@company.com --passwd 'MyP@ss'
```

**Comment by austinmama** [comment]
Closing issue.  Thanks, Sean!
