### ISSUE TITLE
Windows download link not working

### ISSUE THREAD

**Issue by fabriciomtzi** [ibm-cloud-docs/iaas-vpn#26]
https://cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-standalone-vpn-clients

**Comment by austinmama** [comment]
Staging server now points to the Array download site.  IBM is no longer hosting the packages.  Closing since this will no longer be an issue.  

https://test.cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-standalone-vpn-clients
