### ISSUE TITLE
IBM Cloud doc should not reference MS doc

### ISSUE THREAD

**Issue by DRoiDonCloud** [ibm-cloud-docs/iaas-vpn#31]
Hi guys,

My two cents... we should have our own reference for what is VPN, and how to troubleshoot. Referring to MS documentation is not appropriate IMO given they are our direct competitor. I would find vendor-agnostic references if possible. Please reach out to me or Chris Biehle if you need help.

Thanks,
Denis

**Comment by lilorozco** [comment]
I will move this issue to our internal github for tracking purposes.
