### ISSUE TITLE
Issues accessing MacOS 10.15 and higher

### ISSUE THREAD

**Issue by lgillesp-gars** [ibm-cloud-docs/iaas-vpn#33]
As of MacOS Catalina (ie. 10.15.x and up) NPAPI support is no longer available in ANY BROWSER on the Mac and the new Version of MotionPro+ is a disaster and doesn't work either (it is a 32bit app and Catalina and Windows 10 both no longer support 32 bit apps).  What are we now supposed to use?  By the way, this is also true of Windows 10.

**Comment by austinmama** [comment]
Per IaaS VPN Support, this issue was previously fixed.  Closing outdated Git issue.
