### ISSUE TITLE
All software related to VPN connection is outdated and/or insecure

### ISSUE THREAD

**Issue by gianlucabonetti** [ibm-cloud-docs/iaas-vpn#36]
On Windows, you required ActiveX components which cannot be used any more.

On Linux, you require a Java applet plugin which cannot be used any more.

It's year 2020 and your VPN documentation seems to be stuck in year 2000.

**Comment by austinmama** [comment]
ActiveX and Java plug-ins no longer required. IBM now offers stand-alone VPN clients for OSs.  Closing outdated Git issue.
