### ISSUE TITLE
Using a Browser instructions need to be updated

### ISSUE THREAD

**Issue by DebraCip** [ibm-cloud-docs/iaas-vpn#37]
Per one of my SMEs, Graham Hardy:

Using VPN to access your instance using the documentation here https://cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=iaas-vpn-getting-started is well documented but doesn't work if you follow the steps, which are clearly laid out until you get to the point "Using a Browser". 

So straight from the word go, the VPN sites do not support Chrome or Microsoft Edge. In fact if you use a browser like Mozilla Firefox and try to access the login page and attempt a log in, you will be met with the same challenge (the login box is greyed out not allowing you to type anything). This is because these browsers no longer support NPAPI. The VPN website does work with Microsoft Internet Explorer 11 and you can use your VPN credentials to log in. But I would suggest using the MotionPro application.
 
The  only alternative is to use the "Standalone VPN client software".  Currently I have tested MotionPro and could not connect to the vpn.fra02.softlayer.com. When I reported this issue to the Helpdesk they confirmed that the Frankfurt Softlayer VPN server had real issues so I pointed the tool instead to vpn.lon02.softlayer.com:443 instead and this worked. 
For a list of available VPN  Endpoints check the link VPN Endpoints

As from Internet chat rooms concerning cloud and IBM Cloud this has been an issue for 3 years, so I thought I would try and see if this has been resolved, clearly it has not and your only options are Safari, MIE11 or using the standalone MotionPro application. 

As an entry level task it would be irresponsible for the Cloud guys to let this continue, especially if the First Impressions on customers creating a sandbox system and test driving the Virtual Server are negative.

**Comment by austinmama** [comment]
Online version has been modified to no longer require Java applications.  Closing outdated Git issue as Fixed.
