### ISSUE TITLE
Add vpn endpoint for Milan region

### ISSUE THREAD

**Issue by koyadume** [ibm-cloud-docs/iaas-vpn#38]
I can see that [this](https://cloud.ibm.com/docs/iaas-vpn?topic=iaas-vpn-available-vpn-endpoints) page does not mention vpn endpoint (https://vpn.mil01.softlayer.com/prx/000/http/localhost/login) for milan region. Kindly update same.

**Comment by austinmama** [comment]
Fixed.  Points to website now w/ Milan endpoint: https://www.ibm.com/cloud/vpn-access
