### ISSUE TITLE
MotionPro Plus does not work

### ISSUE THREAD

**Issue by xzlin** [ibm-cloud-docs/iaas-vpn#40]
https://cloud.ibm.com/docs/iaas-vpn?topic=iaas-vpn-connect-ssl-vpn-mac-osx mentioned MotionPro Plus as the vpn client for IBM Cloud vpn access. It does not work.

https://cloud.ibm.com/docs/iaas-vpn?topic=iaas-vpn-connect-ssl-vpn-mac-osx
![image](https://user-images.githubusercontent.com/5461709/98054482-e74e7500-1def-11eb-90dd-6bdd5861baf9.png)

**Comment by austinmama** [comment]
Fixed already.  Closing outdated Git issue.
