### ISSUE TITLE
"Available endpoints" link is redirecting to wrong page

### ISSUE THREAD

**Issue by dotch3** [ibm-cloud-docs/iaas-vpn#47]
**Description:**
the. "available VPN endpoints" link on  page is redirecting to a wrong page, it is  "TEST" environment instead of "CLOUD.IBM.COM"   

this the href/page opened with the clink currently -> (https://test.cloud.ibm.com/docs/iaas-vpn?topic=iaas-vpn-available-vpn-endpoints&_gl=1*1cmkxdd*_ga*MTY4MzI4NjA2MS4xNjkwNjUwODcw*_ga_FYECCCS21D*MTY5MTQwOTA4MS4xOS4xLjE2OTE0MDk0NTEuMC4wLjA.).

**Current Result:** Page opened: https://test.cloud.ibm.com/docs/iaas-vpn?topic=iaas-vpn-available-vpn-endpoints&_gl=1*tdi3t1*_ga*MTY4MzI4NjA2MS4xNjkwNjUwODcw*_ga_FYECCCS21D*MTY5MTQwOTA4MS4xOS4xLjE2OTE0MDk2MjQuMC4wLjA.
**Expected:** open the page : https://cloud.ibm.com/docs/iaas-vpn?topic=iaas-vpn-available-vpn-endpoints

![image](https://github.com/ibm-cloud-docs/iaas-vpn/assets/9809022/9e45b0f2-15d9-4b2a-9ef6-b968e5cceb33)

**Comment by austinmama** [comment]
Fixed.  Build is running now.  Thank you for your feedback!
