### ISSUE TITLE
Sao Paulo VPN Endpoint - Bad Request

### ISSUE THREAD

**Issue by kevin-anadon** [ibm-cloud-docs/iaas-vpn#48]
Hi, the URL of South America, Sao Paulo VPN is wrong.
Greetings

**Comment by austinmama** [comment]
@kevin-anadon Hi Kevin!  Will get that fixed.  Thanks for reporting.

**Comment by ying-tang** [comment]
Hi Kevin, the SAO endpoint is back. Please verify: [vpn.sao.softlayer.com](https://vpn.sao.softlayer.com/)

**Comment by ying-tang** [comment]
@kevin-anadon Hi Kevin, can you verify again? https://vpn.sao.softlayer.com/ looks find to us.

**Comment by kevin-anadon** [comment]
> @kevin-anadon Hi Kevin, can you verify again? https://vpn.sao.softlayer.com/ looks fine to us. 

Hi, yeah the URL was okay, the link in the VPN endpoints doc was wrong.
I attach the error:
![Screenshot_2023-11-08-08-24-35-704_com.android.chrome-edit.jpg](https://github.com/ibm-cloud-docs/iaas-vpn/assets/64451201/d84184a0-8228-4758-ba9e-6cf2cf969c3c)

**Comment by austinmama** [comment]
Updated!  Thank you for bringing to our attention.  Had an extra / at the end of the URL.
