### ISSUE TITLE
vpn.fra02.softlayer.com seems to be down of should be removed from the docs if it is not longer available

### ISSUE THREAD

**Issue by Daniel-Ebert** [ibm-cloud-docs/iaas-vpn#49]
https://cloud.ibm.com/docs/iaas-vpn?topic=iaas-vpn-available-vpn-endpoints

[vpn.fra02.softlayer.com](https://vpn.fra02.softlayer.com/) was down the last week so I would like to initiate to check the docs/whether the VPN endpoint still exists.

**Comment by austinmama** [comment]
Please use https://vpn.fra.softlayer.com/prx/000/http/localhost/login/index.html  -- fra02 was removed
